In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
car_price = pd.read_csv('/content/car_age_price.csv')

In [4]:
car_price.head()

   Year   Price
0  2018  465000
1  2019  755000
2  2019  700000
3  2018  465000
4  2018  465000

In [5]:
car_price.columns

Index(['Year', 'Price'], dtype='object')

In [6]:
car_price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    112 non-null    int64
 1   Price   112 non-null    int64
dtypes: int64(2)
memory usage: 1.9 KB

In [7]:
car_price.corr()

           Year     Price
Year   1.000000  0.776302
Price  0.776302  1.000000

In [8]:
#feature - target splitting
y = car_price[['Price']]
x = car_price[['Year']]

In [9]:
# train - test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [10]:
#creating linear regression model
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model = lr.fit(X_train,y_train)

In [11]:
model.fit(X_train, y_train)

LinearRegression()

In [12]:
y_pred = model.predict(X_test)

In [13]:
y_test

      Price
40   525000
65   495000
4    465000
47   450000
42   550000
69   300000
26   550000
11   500000
10   500000
44   550000
73   320000
55   550000
68   465000
97   640000
0    465000
18   500000
53   345000
80   390000
103  375000
91   520000
36   550000
12   500000
31   550000

In [14]:
y_pred

array([[600775.91252081],
       [505558.77690466],
       [553167.34471273],
       [553167.34471273],
       [553167.34471273],
       [410341.6412885 ],
       [505558.77690466],
       [553167.34471273],
       [600775.91252081],
       [600775.91252081],
       [315124.50567235],
       [505558.77690466],
       [410341.6412885 ],
       [648384.48032889],
       [553167.34471273],
       [600775.91252081],
       [315124.50567235],
       [410341.6412885 ],
       [505558.77690466],
       [505558.77690466],
       [505558.77690466],
       [505558.77690466],
       [505558.77690466]])

In [15]:
from sklearn.metrics import mean_squared_error,r2_score
print(mean_squared_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

4326906256.829671
0.36759313425902185

In [16]:
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)
r2 = r2_score(y_test, y_pred)
print("R-squared:", r2)

Mean Squared Error: 4326906256.829671
R-squared: 0.36759313425902185

In [17]:
#making prediction for year
price_pred = model.predict([[2022]])
price_pred

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[743601.61594504]])

## Lasso Regression

In [18]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

print("R-squared:", r2_score(y_test, y_pred))
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))

R-squared: 0.36759313425902185
Mean Absolute Error: 53534.77957001264
Mean Squared Error: 4326906256.829671

In [19]:
from sklearn.metrics import mean_squared_error, r2_score

y_pred_lasso = model.predict(X_test)

mse_lasso = mean_squared_error(y_test, y_pred_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)

print("Lasso Mean Squared Error:", mse_lasso)
print("Lasso R-squared:", r2_lasso)

Lasso Mean Squared Error: 4326906256.829671
Lasso R-squared: 0.36759313425902185

In [20]:
print("Linear Regression R2:",r2)
print("Lasso Regression R2:", r2_lasso)

Linear Regression R2: 0.36759313425902185
Lasso Regression R2: 0.36759313425902185

## Lasso Regression performs slightly better than Linear Regression based on R² score